### ISSUE TITLE
How can I annotate each cluster with a singer

### ISSUE THREAD

**Issue by xjsun1221** [BiocPy/singler#27]
In the R package `singleR`, I am able to utilize the `cluster` parameter; however, it appears that this parameter does not exist in the Python version of `singler`.Did I miss anything？

**Comment by xjsun1221** [comment]
> **scranpy** has an `aggregate_across_cells()` function that you can use to get the aggregated matrix that can be used in `classify_single_reference()`. That should be the same as what `SingleR::SingleR()` does under the hood.
> 
> I suppose we _could_ add this argument, but to be honest, the only reason that `cluster=` still exists in `SingleR()` is for back-compatibility purposes. It's easy enough to do the aggregation outside of the function and I don't want to add more responsibilities to the **singler** package.

it works,thank you very much

**Comment by jkanche** [comment]
closing this, let us know if you run into any issues.

**Comment by xjsun1221** [comment]
> closing this, let us know if you run into any issues.

Thank you. I've been learning singler recently. According to the quick start guide on the pip website,the `test_data` parameter seems to require the **original count data**:
```
data = sce.read_tenx_h5("pbmc4k-tenx.h5", realize_assays=True)
mat = data.assay("counts")
```
However, the R version of SingleR typically uses **log-normalized data**. 
﻿
The documentation also mentions,”or if you are coming from scverse ecosystem, i.e. AnnData, simply read the object as SingleCellExperiment and extract the matrix and the features.“，but data processed with Scanpy could be extracted as **scaled data**.
﻿
Could you provide advice on which matrix I should use, or if either would be suitable?
﻿

**Comment by LTLA** [comment]
For the test dataset, it doesn't matter. Only the ranks of the values are used by **SingleR** itself, so it will give the same results for any monotonic transformation within each cell.

IIRC the only place where the log/normalization-status makes a difference is in `SingleR::plotMarkerHeatmap()` (R package only, not in the Python package yet) which computes log-fold changes in the test dataset to prioritize the markers to be visualized in the heatmap. This is for diagnostic purposes only.

Of course, the reference dataset should always be some kind of log-normalized value, as log-fold changes are computed via the difference of means, e.g., with `getClassicMarkers()`.

**Comment by xjsun1221** [comment]
yeah，thanks a lot.If my scaled data only contains 2000 genes, can I use it? I've found that it may lead to changes in the results.
